var EditorEvent = (function () {
    function EditorEvent() {
    }
    EditorEvent.CIRCLE_BORDER_CHANGED = "CIRCLE_BORDER_CHANGED";
    EditorEvent.BORDER_CHANGED = "BORDER_CHANGED";
    EditorEvent.CONSTELLATIONS_CHANGED = "CONSTELLATIONS_CHANGED";
    EditorEvent.STARS_CHANGED = "STARS_CHANGED";
    EditorEvent.TEXT_1_CHANGED = "TEXT_1_CHANGED";
    EditorEvent.TEXT_2_CHANGED = "TEXT_2_CHANGED";
    EditorEvent.CITY_CHANGED = "CITY_CHANGED";
    EditorEvent.CITY_VISIBILITY_CHANGED = "CITY_VISIBILITY_CHANGED";
    EditorEvent.COORDINATES_CHANGED = "COORDINATES_CHANGED";
    EditorEvent.COORDINATES_VISIBILITY_CHANGED = "COORDINATES_VISIBILITY_CHANGED";
    return EditorEvent;
}());
//# sourceMappingURL=EditorEvent.js.map