var EditorEvent = (function () {
    function EditorEvent() {
    }
    EditorEvent.CIRCLE_BORDER_CHANGED = "CIRCLE_BORDER_CHANGED";
    EditorEvent.BORDER_CHANGED = "BORDER_CHANGED";
    EditorEvent.CONSTELLATIONS_CHANGED = "CONSTELLATIONS_CHANGED";
    EditorEvent.STARS_CHANGED = "STARS_CHANGED";
    EditorEvent.PLACE_LABELS_CHANGED = "PLACE_LABELS_CHANGED";
    EditorEvent.PLACEMENT_CHANGED = "PLACEMENT_CHANGED";
    EditorEvent.TEXT_1_CHANGED = "TEXT_1_CHANGED";
    EditorEvent.TEXT_2_CHANGED = "TEXT_2_CHANGED";
    EditorEvent.CITY_CHANGED = "CITY_CHANGED";
    EditorEvent.CITY_VISIBILITY_CHANGED = "CITY_VISIBILITY_CHANGED";
    EditorEvent.COORDINATES_CHANGED = "COORDINATES_CHANGED";
    EditorEvent.COORDINATES_VISIBILITY_CHANGED = "COORDINATES_VISIBILITY_CHANGED";
    EditorEvent.DATE_TIME_CHANGED = "DATE_TIME_CHANGED";
    EditorEvent.DATE_VISIBILITY_CHANGED = "DATE_VISIBILITY_CHANGED";
    EditorEvent.TIME_VISIBILITY_CHANGED = "TIME_VISIBILITY_CHANGED";
    EditorEvent.SET_CURRENT_DATE_TIME = "SET_CURRENT_DATE_TIME";
    return EditorEvent;
}());
//# sourceMappingURL=EditorEvent.js.map